LotusPark/LotusPark/Models/Reservas.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LotusPark.Models {
    public class Reservas {

        public Reservas() { 
        
            ListaVagas = new HashSet<Vagas>(); 
            ListaFuncionario = new HashSet<Funcionarios>();
        
        }

        /// <summary>
        /// Id da reserva
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Data de início da reserva
        /// </summary>
        [Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
        [DisplayName("Data de Entrada")]
        public DateTime DataEntrada { get; set; }

        /// <summary>
        /// Data de fim da reserva
        /// </summary>
        [Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
        [DisplayName("Data de Saída")]
        public DateTime DataSaida { get; set; }

        /// <summary>
        /// Estado da reserva
        /// </summary>
        [DisplayName("Estado da Reserva")]
        public string Estado { get; set; }

        //*********************************************

        /// <summary>
        /// FK do cliente que fez a reserva
        /// </summary>
        [ForeignKey(nameof(Cliente))]
        public int ClienteFK { get; set; }
        public Clientes? Cliente { get; set; }

        /// <summary>
        /// Lista de vagas que foram reservadas
        /// </summary>
        public ICollection<Vagas> ListaVagas { get; set; }

        /// <summary>
        /// Lista de funcionarios que foram designados para a reserva
        /// </summary>
        public ICollection<Funcionarios> ListaFuncionario { get; set; }
    }
}

LotusPark/LotusPark/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LotusPark.Data;
using LotusPark.Models;
using Microsoft.AspNetCore.Authorization;

namespace LotusPark.Controllers
{
    [Authorize]
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _bd;

        public ClientesController(ApplicationDbContext context)
        {
            _bd = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _bd.Clientes != null ? 
                          View(await _bd.Clientes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Clientes'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _bd.Clientes == null)
            {
                return NotFound();
            }

            var clientes = await _bd.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,NIF,Telefone,Email,CodPostal,Morada,DataNascimento")] Clientes clientes)
        {
            if (ModelState.IsValid)
            {
                _bd.Add(clientes);
                await _bd.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clientes);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _bd.Clientes == null)
            {
                return NotFound();
            }

            var clientes = await _bd.Clientes.FindAsync(id);
            if (clientes == null)
            {
                return NotFound();
            }
            return View(clientes);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,NIF,Telefone,Email,CodPostal,Morada,DataNascimento")] Clientes clientes)
        {
            if (id != clientes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bd.Update(clientes);
                    await _bd.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientesExists(clientes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clientes);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _bd.Clientes == null)
            {
                return NotFound();
            }

            var clientes = await _bd.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_bd.Clientes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Clientes'  is null.");
            }
            var clientes = await _bd.Clientes.FindAsync(id);
            if (clientes != null)
            {
                _bd.Clientes.Remove(clientes);
            }
            
            await _bd.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientesExists(int id)
        {
          return (_bd.Clientes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LotusPark/LotusPark/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LotusPark.Data;
using LotusPark.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace LotusPark.Controllers
{
    [Authorize]
    public class ReservasController : Controller
    {
        private readonly ApplicationDbContext _bd;
        private readonly UserManager<IdentityUser> _userManager;
        public ReservasController(ApplicationDbContext context, UserManager<IdentityUser> userManager) {
            _userManager = userManager;
            _bd = context;
        }

        // GET: Reservas
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Cliente")) {
                string idDaPessoaQueEstaAutenticada = _userManager.GetUserId(User);
                var reservas = await _bd.Reservas.Include(r => r.Cliente).Where(a => a.Cliente.UserId == idDaPessoaQueEstaAutenticada).ToListAsync();
                return View(reservas);
            }
            var todasReservas = await _bd.Reservas.Include(r => r.Cliente).ToListAsync();
            return View(todasReservas);
            
        }

        // GET: Reservas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _bd.Reservas == null)
            {
                return NotFound();
            }

            /* procurarm, na base de dados, a raserva com ID igual ao parâmetro fornecido
             * SELECT *
             * 
             * 
             */
            var reserva = await _bd.Reservas
                .Include(r => r.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // GET: Reservas/Create
        /// <summary>
        /// Criar as condições para a View de criação de uma reserva
        /// ser enviada para o browser
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            // prepara os dados a serem apresentados na dropwdown
            ViewData["ClienteFK"] = new SelectList(_bd.Clientes, "Id", "Nome");

            // invoca a view
            return View();
        }

        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DataEntrada,DataSaida,Estado,ClienteFK")] Reservas reservas)
        {
            if (ModelState.IsValid)
            {
                _bd.Add(reservas);
                await _bd.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteFK"] = new SelectList(_bd.Clientes, "Id", "Nome");
            return View(reservas);
        }

        // GET: Reservas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _bd.Reservas == null)
            {
                return NotFound();
            }

            var reservas = await _bd.Reservas.FindAsync(id);
            if (reservas == null)
            {
                return NotFound();
            }
            ViewData["ClienteFK"] = new SelectList(_bd.Clientes, "Id", "Id", reservas.ClienteFK);
            return View(reservas);
        }

        // POST: Reservas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataEntrada,DataSaida,Estado,ClienteFK")] Reservas reservas)
        {
            if (id != reservas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bd.Update(reservas);
                    await _bd.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservasExists(reservas.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteFK"] = new SelectList(_bd.Clientes, "Id", "Id", reservas.ClienteFK);
            return View(reservas);
        }

        // GET: Reservas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _bd.Reservas == null)
            {
                return NotFound();
            }

            var reservas = await _bd.Reservas
                .Include(r => r.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservas == null)
            {
                return NotFound();
            }

            return View(reservas);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_bd.Reservas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Reservas'  is null.");
            }
            var reservas = await _bd.Reservas.FindAsync(id);
            if (reservas != null)
            {
                _bd.Reservas.Remove(reservas);
            }
            
            await _bd.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservasExists(int id)
        {
          return (_bd.Reservas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LotusPark/LotusPark/Views/Reservas/Create.cshtml
@model LotusPark.Models.Reservas

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<h4>Reservas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataEntrada" class="control-label"></label>
                <input asp-for="DataEntrada" class="form-control" />
                <span asp-validation-for="DataEntrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataSaida" class="control-label"></label>
                <input asp-for="DataSaida" class="form-control" />
                <span asp-validation-for="DataSaida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <select asp-for="ClienteFK" class ="form-control" asp-items="ViewBag.ClienteFK"></select>
            </div>
            </br>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
            </br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LotusPark/LotusPark/Views/Reservas/Delete.cshtml
@model LotusPark.Models.Reservas

@{
    ViewData["Title"] = "Apagar";
}

<h1>Apagar</h1>

<h3>Tem a certeza que deseja apagar esta reserva?</h3>
<div>
    <h4>Reservas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataEntrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataEntrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataSaida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataSaida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à Lista</a>
    </form>
</div>

LotusPark/LotusPark/Views/Reservas/Details.cshtml
@model LotusPark.Models.Reservas

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Reservas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataEntrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataEntrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataSaida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataSaida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            <a asp-action="Details"
               asp-controller="Clientes" 
               asp-route-id="@Model?.Cliente.Id">
               @Html.DisplayFor(model => model.Cliente.Nome)
            </a>
        </dd>
    </dl>
</div>
<div>
    @if (!User.IsInRole("Cliente"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Editar |</a>
    }
    <a asp-action="Index">Voltar à Lista</a>
</div>

LotusPark/LotusPark/Views/Reservas/Edit.cshtml
@model LotusPark.Models.Reservas

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Reservas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DataEntrada" class="control-label"></label>
                <input asp-for="DataEntrada" class="form-control" />
                <span asp-validation-for="DataEntrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataSaida" class="control-label"></label>
                <input asp-for="DataSaida" class="form-control" />
                <span asp-validation-for="DataSaida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <select asp-for="ClienteFK" class="form-control" asp-items="ViewBag.ClienteFK"></select>
                <span asp-validation-for="ClienteFK" class="text-danger"></span>
            </div>
            </br>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
            </br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LotusPark/LotusPark/Views/Reservas/Index.cshtml
@model IEnumerable<LotusPark.Models.Reservas>

@{
    ViewData["Title"] = "Lista de Reservas";
}

<h1>Lista de Reservas</h1>
<p>
    <a asp-action="Create">Nova Reserva</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DataEntrada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataSaida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            @if (!User.IsInRole("Cliente")) {
                <th>
                    @Html.DisplayNameFor(model => model.Cliente)
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataEntrada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataSaida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            @if (!User.IsInRole("Cliente"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.Nome)
                </td>
            }

            @if (User.IsInRole("Cliente"))
            {
                <td>
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                </td>
            }else{
                <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
                </td>
                }
        </tr>
}
    </tbody>
</table>